CREATE TABLE BADGES (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	surname TEXT NOT NULL
);

CREATE TABLE MOVEMENTS (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	badge TEXT NOT NULL,
	date_time TEXT NOT NULL
	
);
